version: "2.1"
services:
    airflow_db:
        image: postgres:10.11
        container_name: airflow_db
        env_file:
            - .env
        ports:
            - "5432:5432"

    airflow_web:
        build: ./airflow-pipeline
        container_name: airflow_web
        image: asatrya/docker-airflow:1.10.9
        restart: always
        depends_on:
            - airflow_db
        env_file:
            - .env
        environment:
            EXECUTOR: "LocalExecutor"
        volumes:
            - ./airflow-pipeline/dags:/usr/local/airflow/dags
            # Uncomment to override airflow.cfgs
            - ./airflow-pipeline/airflow.cfg:/usr/local/airflow/airflow.cfg
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"

volumes: 
    vol-data-lake: