version: "2.1"
services:
    airflow_db:
        image: postgres:10.11
        env_file:
            - .env
        ports:
            - "5432:5432"

    airflow_web:
        build: ./airflow-pipeline
        image: asatrya/docker-airflow:1.10.6
        restart: always
        depends_on:
            - airflow_db
        env_file:
            - .env
        environment:
            EXECUTOR: "LocalExecutor"
        volumes:
            - ./airflow-pipeline/dags:/usr/local/airflow/dags
            # Uncomment to override airflow.cfgs
            # - ./airflow-pipeline/airflow.cfg:/usr/local/airflow/airflow.cfg
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"

    data_source:
        image: minio/minio:RELEASE.2019-10-12T01-39-57Z
        volumes:
            - ./data-source/data:/data
        ports:
            - "9001:9000"
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        command: server /data

    data_lake:
        image: minio/minio:RELEASE.2019-10-12T01-39-57Z
        volumes:
            - vol-data-lake:/data
        ports:
            - "9002:9000"
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        command: server /data

    data_warehouse:
        image: mysql:5.6
        env_file:
            - .env
        volumes: 
            - ./data-warehouse/sql:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"

volumes: 
    vol-data-lake: